######################################################################
# Automatically generated by qmake (3.1) Wed Sep 13 16:27:32 2017
######################################################################

QT += core gui widgets

TEMPLATE = app
TARGET = clock_on_desktop
INCLUDEPATH += .

# Input
FORMS += clockondesktop.ui
SOURCES += main.cpp \
    clockondesktop.cpp

HEADERS += \
    clockondesktop.h
